export const enum CATEGORY {
    CHEST = "CHEST",
    BACK = "BACK",
    SHOULDERS = "SHOULDERS",
    BICEPS = "BICEPS",
    TRICEPS = "TRICEPS",
    LEGS = "LEGS",
    GLUTES = "GLUTES",
    ABS = "ABS",
    FULL_BODY = "FULL_BODY",
    CARDIO = "CARDIO",
    UNCATEGORIZED = "UNCATEGORIZED",
}